"""Create tables owners, pets

Revision ID: 234e59b159d8
Revises: 
Create Date: 2024-03-14 03:24:15.406564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234e59b159d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
